# Generated by Django 4.2.1 on 2023-05-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.CharField(default='https://th.bing.com/th/id/R.78aab76606113ad8d781df4cfdfe4787?rik=g34KT78av2NJgg&pid=ImgRaw&r=0', max_length=600),
        ),
    ]
