# Generated by Django 4.2.1 on 2023-10-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_customer_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='desc',
            field=models.CharField(default='love', max_length=200),
            preserve_default=False,
        ),
    ]
